learn:
	python3 scenario-learning/main.py data/learn.conf

generate:
	./scenario-generation/entitygen data/gen.conf
	./scenario-generation/datagen data/gen.conf
	./scenario-generation/obsgen data/gen.conf
